export const AdminUserListData = [
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
  {
    name: 'John Doe',
    account: 'heyjohn',
    avatar: null,
    banner: null,
    totalTweets: '1.5k',
    totalLikes: '20k',
    following: 34,
    follower: 59,
  },
]
